version: '3.4'

services:
  maindb:
    container_name: maindb
    environment:
        SA_PASSWORD: "123jaja123"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1434:1433"

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  security.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=maindb;Database=Security.Api;User Id=sa;Password=123jaja123"  
    depends_on: 
      - maindb
    ports:
      - "8000:80"

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=maindb;Database=Order.Api;User Id=sa;Password=123jaja123"  
    depends_on: 
      - maindb
    ports:
      - "8001:80"


  catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=maindb;Database=Catalogue.Api;User Id=sa;Password=123jaja123"  
    depends_on: 
      - maindb
    ports:
      - "8002:80"


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8003:80"

